COMPILE_DEPS = CORE_DEPS + [
    "//core/store/serializers:onos-core-serializers",
    "//apps/netflow/api:onos-apps-netflow-api",
    "@io_netty_netty_common//jar",
    "@io_netty_netty//jar",
]

osgi_jar(
    deps = COMPILE_DEPS,
)
