BUNDLES = [
    "//apps/ipflow-monitor/netflow/api:onos-apps-ipflow-monitor-netflow-api",
    "//apps/ipflow-monitor/netflow/app:onos-apps-ipflow-monitor-netflow-app",
]

onos_app(
    category = "Traffic Monitoring",
    description = "Provides handling of netflow traffic.",
    included_bundles = BUNDLES,
    origin = "ONOS Community",
    title = "Netflow traffic monitoring",
    url = "http://onosproject.org",
)
