COMPILE_DEPS = CORE_DEPS + JACKSON + KRYO + REST + CLI + [
    "//core/store/serializers:onos-core-serializers",
    "//apps/aiplugin/api:onos-apps-aiplugin-api",
]

osgi_jar(
    deps = COMPILE_DEPS,
)
