BUNDLES = [
    "//apps/netflow/api:onos-apps-netflow-api",
    "//apps/netflow/app:onos-apps-netflow-app",
]

onos_app(
    category = "Traffic Monitoring",
    description = "Provides handling of netflow traffic.",
    included_bundles = BUNDLES,
    origin = "ONOS Community",
    title = "Netflow traffic monitoring",
    url = "http://onosproject.org",
)
