BUNDLES = [
    "//apps/aiplugin/api:onos-apps-aiplugin-api",
    "//apps/aiplugin/app:onos-apps-aiplugin-app",
]

onos_app(
    category = "AI",
    description = "ONOS AI plugin application.",
    included_bundles = BUNDLES,
    origin = "ONOS Community",
    title = "ONOS AI plugin ",
    url = "http://onosproject.org",
)
