BUNDLES = [
    "//apps/ipflow-monitor/sflow/api:onos-apps-ipflow-monitor-sflow-api",
    "//apps/ipflow-monitor/sflow/app:onos-apps-ipflow-monitor-sflow-app",
]

onos_app(
    category = "Traffic Monitoring",
    description = "Provides handling of sflow traffic.",
    included_bundles = BUNDLES,
    origin = "ONOS Community",
    title = "Sflow traffic monitoring",
    url = "http://onosproject.org",
)
