BUNDLES = [
    "//apps/bgpmonitoring/api:onos-apps-bgpmonitoring-api",
    "//apps/bgpmonitoring/app:onos-apps-bgpmonitoring-app",
    "//protocols/bgp/bgpio:onos-protocols-bgp-bgpio",
]

onos_app(
    app_name = "org.onosproject.bgpmonitoring",
    category = "BGP Monitoring",
    description = "BGP monitoring protocol application.",
    included_bundles = BUNDLES,
    title = "BGP Monitoring Protocol",
    url = "http://onosproject.org",
)
